---
- hosts: hostList
  serial: 1  # This ensures that the services are deployed in only one host at a time
  vars_files:
    - vars/cinder_info.yml
  tasks:
    - name: apt update
      shell: sudo apt-get update
    - name: install all cinder packages
      shell: sudo apt-get install -y --force-yes cinder-common python-cinder cinder-api cinder-scheduler cinder-volume cinder-backup python-metrics
    - name: Install cinder ec2
      shell: sudo apt-get install -y --force-yes python-cinder-ec2-api
    - name: Stop Services cinder
      service: name={{item}} state=stopped
      become: yes
      with_items: 
        - cinder-api
        - cinder-scheduler
        - cinder-backup
        - cinder-ec2-api
        - cinder-volume
        - oslo-messaging-zmq-receiver
    - name: Start Services cinder api, scheduler, ec2-api, backup
      service: name={{item}} state=started
      become: yes
      with_items:
        - cinder-api
        - cinder-scheduler
        - cinder-ec2-api
        - cinder-backup
        - oslo-messaging-zmq-receiver
