- hosts: hostList
  vars_files:
    - vars/cinder_info.yml
  tasks:
    - name: Copy cer file dir
      copy: src=src/{{cer_files}} dest=/usr/local/share/ca-certificates/
      become: yes
    - name: update certificates
      shell: sudo update-ca-certificates --fresh
